name = "jsa-website-clone"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Configure the worker to serve static assets
[site]
bucket = "./public"

# Configure module rules for text imports
[[rules]]
type = "Text"
globs = ["**/*.css", "**/*.html"]
fallthrough = true
